### PR TITLE
142. Linked List Cycle II

### PR DESCRIPTION
**Pull request by momeemt**
問題: https://leetcode.com/problems/linked-list-cycle-ii/

### CODE REVIEW

**Comment by momeemt** [comment]
https://github.com/tayzarnw/LeetCode/pull/4#discussion_r1546155136

確かに、衝突点の探索と起点の探索は目的が異なるので分けてあった方がわかりやすいかもしれない

**Comment by momeemt** [comment]
https://github.com/cheeseNA/leetcode/pull/7/files#diff-782ea07ed355f2a754eec45d8da8683a29a68e3e364e7eba7a24917fca580398

衝突点の探索が分けられていて読みやすい

**Review by nodchip — APPROVED** [review]
よいと思います。

**Comment by hupptechnologies** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
kabinbear, @sw414, @ahmedx2, @Subby, @leoyoung07, @neo2616, @geheim01, @johncurcio, @Alan-love, @tenebreux, @nitishmakhija, @triet1213, @AladdinCHN, @nathgilson, @hoxizhu, @ampg99, @ya7lelcom, @ProtagonistOfLife, @DeathRisker, @physicsfamily, @ESaller, @eimenanacreado, @ASOEstudio, @kindred77, @RunzhouLi, @rishabjn, @pc-maniac, @ace-yong, @Amoyblack, @cyf-gh, @Mehrdad-Farshi, @Lagrang3, @dnlhwrd3269, @mojtaba13677, @orryjarvis, @15150174451, @MrXiong, @lybyyy, @MateeBoonkuh, @Jonahmoon, @zip520123, @doodeehee70, @Joeycz, @jonasvanbuel, @liuxh-go, @donnielrt, @MajorTom327, @PsySc0rpi0n, @leonlibraries, @Sehan123

**Pull request merged**
